### ISSUE TITLE
Adding events after loading JSON data

### ISSUE THREAD

**Issue by 3-14159jam** [CleverPumpkin/CrunchyCalendar#14]
First of all, I really love this calendar. I have tried a lot of calendars in the past few days but this was by far the best and easiest to implement.

I am currently having an issue with reloading the event indicators after loading JSON from the google Calendar API. The calendar runs the generateCalendarDateIndicators() function before the data is there however when I run it manually after I have the data, no new dots appear. I am currently running the code inside of its own activity instead of a fragment.

I am imagining that I need to have the calendar refresh the UI once I have the JSON data. I have tried a few different ideas for refreshing the UI but they all lead to refreshing the entire page which puts me in a big circle.

Any thoughts or suggestions would be well appreciated.

**Comment by alexsurinov** [comment]
Hi and thanks for the feedback!

It's strange, because the Calendar was designed in such a way that each time when you are setting indicators (`calendarView.datesIndicators = indicatorsList`) the Calendar view is updated to display new indicators. 

I have tested this scenario and all works fine:
1. Init the Calendar  with `setupCalendar()` method
2. Asynchronously load some data for the Calendar then generate and set dates indicators (`calendarView.datesIndicators = indicatorsList`) 
3. New indicators are displayed

**Comment by pavelsust** [comment]
how you add events?? i am stack on this. I can't add a date into the calendar as a event.
